### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by hnrysmth** [basekit/google-webfonts-json-encoder#1]
```bash
$ ./node_modules/.bin/mocha test/lib/

/Users/hnrysmth/src/google-webfonts-json-encoder/test/lib/argsValidator.test.js:4
    const assert = require('assert');
    ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/hnrysmth/src/google-webfonts-json-encoder/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/hnrysmth/src/google-webfonts-json-encoder/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/hnrysmth/src/google-webfonts-json-encoder/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/hnrysmth/src/google-webfonts-json-encoder/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by hnrysmth** [comment]
Getting the same thing when I run `index.js` too.

```bash
$ ./index.js 

/Users/hnrysmth/src/google-webfonts-json-encoder/index.js:5
const config = require('./config'),
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by ejosafat** [comment]
Node version?

**Comment by hnrysmth** [comment]
```
$ node --version
v0.10.33
```

**Comment by hnrysmth** [comment]
I've upgraded to the latest using `brew update; brew upgrade node` and it's still happening :( 

```bash
$ node --version
v0.12.2
$ node index.js 
/Users/hnrysmth/src/google-webfonts-json-encoder/index.js:5
const config = require('./config'),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by hnrysmth** [comment]
Fixed by using the `--harmony` flag!

**Comment by wudeliang** [comment]
node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/haodaibao/Desktop/React Native/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
